"""ondelete cascade in user private recipes model

Revision ID: 78ea33110b9a
Revises: 4229ae917b07
Create Date: 2022-03-04 11:53:45.271179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea33110b9a'
down_revision = '4229ae917b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_private_recipes_recipe_id_fkey', 'user_private_recipes', type_='foreignkey')
    op.drop_constraint('user_private_recipes_user_id_fkey', 'user_private_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'user_private_recipes', 'users', ['user_id'], ['auth_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_private_recipes', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_private_recipes', type_='foreignkey')
    op.drop_constraint(None, 'user_private_recipes', type_='foreignkey')
    op.create_foreign_key('user_private_recipes_user_id_fkey', 'user_private_recipes', 'users', ['user_id'], ['auth_id'])
    op.create_foreign_key('user_private_recipes_recipe_id_fkey', 'user_private_recipes', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
