"""Table recipes created

Revision ID: 85f939060477
Revises: 
Create Date: 2022-02-28 13:26:50.918140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85f939060477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', postgresql.ENUM('Doce', 'Salgado', 'Bebida', name='category'), nullable=False),
    sa.Column('ingredients', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('instructions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('preparation_time', sa.DateTime(), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('Fácil', 'Intermediário', 'Difícil', name='difficulty'), nullable=False),
    sa.Column('portion_size', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
