"""cacascade delete in favorite_recipes_model

Revision ID: 890d54769c3d
Revises: 78ea33110b9a
Create Date: 2022-03-04 11:56:35.517835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890d54769c3d'
down_revision = '78ea33110b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_recipes_user_id_fkey', 'favorite_recipes', type_='foreignkey')
    op.drop_constraint('favorite_recipes_recipe_id_fkey', 'favorite_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_recipes', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorite_recipes', 'users', ['user_id'], ['auth_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_recipes', type_='foreignkey')
    op.drop_constraint(None, 'favorite_recipes', type_='foreignkey')
    op.create_foreign_key('favorite_recipes_recipe_id_fkey', 'favorite_recipes', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key('favorite_recipes_user_id_fkey', 'favorite_recipes', 'users', ['user_id'], ['auth_id'])
    # ### end Alembic commands ###
