"""cascade delete on recipes_rating_model

Revision ID: 90fc9c4d8711
Revises: 890d54769c3d
Create Date: 2022-03-04 11:57:36.733625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fc9c4d8711'
down_revision = '890d54769c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_rating_user_id_fkey', 'recipes_rating', type_='foreignkey')
    op.drop_constraint('recipes_rating_recipe_id_fkey', 'recipes_rating', type_='foreignkey')
    op.create_foreign_key(None, 'recipes_rating', 'users', ['user_id'], ['auth_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipes_rating', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes_rating', type_='foreignkey')
    op.drop_constraint(None, 'recipes_rating', type_='foreignkey')
    op.create_foreign_key('recipes_rating_recipe_id_fkey', 'recipes_rating', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key('recipes_rating_user_id_fkey', 'recipes_rating', 'users', ['user_id'], ['auth_id'])
    # ### end Alembic commands ###
