"""created column preparation_time

Revision ID: a96c45d589e1
Revises: b55af1c9b6d6
Create Date: 2022-03-07 13:03:11.271474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96c45d589e1'
down_revision = 'b55af1c9b6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('preparation_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'preparation_time')
    # ### end Alembic commands ###
