"""deleted preparation_time column

Revision ID: b55af1c9b6d6
Revises: 90fc9c4d8711
Create Date: 2022-03-07 13:02:28.109510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b55af1c9b6d6'
down_revision = '90fc9c4d8711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'preparation_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('preparation_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
