"""recipes model table created

Revision ID: c021898cde66
Revises: 058b9f7c21ad
Create Date: 2022-03-02 13:27:53.695982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c021898cde66'
down_revision = '058b9f7c21ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', postgresql.ENUM('Doce', 'Salgado', 'Bebida', name='Category'), nullable=False),
    sa.Column('ingredients', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('instructions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('preparation_time', sa.Time(), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('Fácil', 'Intermediário', 'Difícil', name='Difficulty'), nullable=False),
    sa.Column('portion_size', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
