"""create users table

Revision ID: c05740a9af49
Revises: 058b9f7c21ad
Create Date: 2022-03-02 13:23:44.236955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c05740a9af49'
down_revision = '058b9f7c21ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('auth_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', postgresql.ENUM('Feminino', 'Masculino', 'Outro', name='gender'), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
