"""created relationship with user

Revision ID: d3e4a2ebaf7c
Revises: a96c45d589e1
Create Date: 2022-03-09 10:56:31.370376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e4a2ebaf7c'
down_revision = 'a96c45d589e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
